Algoritmo "Exercício 001"
// Disciplina: [Algoritmo]
// Professor: Gustavo Guanabara
// Descrição: Aqui você descreve o que o programa faz! (função)
// Autor: Cidy Sampaio da Silva
// Data: 29/12/2023

// 1) Escreva um programa que mostre na tela a mensagem "Olá, Mundo!"
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Escreva ("Olá, mundo!")

Fimalgoritmo